version: '3'
services:
  db:
    image: mongo:latest
    volumes:
      - ./mounts/data/db:/data/db
  web:
    image: b2bikes-api-img
    depends_on:
      - db
    ports:
      - 3000:3000
    command: ["./wait-for-it.sh", "db:27017", "--strict", "--", "npm", "start"]
    environment:
      MONGO_URI: "mongodb://db:27017/b2bikes-db"